INSERT INTO public.genre (id, language_id, name) VALUES (1, 2, 'Научная фантастка');
INSERT INTO public.genre (id, language_id, name) VALUES (1, 1, 'Science fiction');
INSERT INTO public.genre (id, language_id, name) VALUES (2, 1, 'Computers & Technology');
INSERT INTO public.genre (id, language_id, name) VALUES (2, 2, 'Компьютерные технологии');
INSERT INTO public.genre (id, language_id, name) VALUES (3, 1, 'Social Science');
INSERT INTO public.genre (id, language_id, name) VALUES (3, 2, 'Публицистика');
INSERT INTO public.genre (id, language_id, name) VALUES (4, 1, 'Autobiography');
INSERT INTO public.genre (id, language_id, name) VALUES (4, 2, 'Автобиография');
INSERT INTO public.genre (id, language_id, name) VALUES (5, 1, 'Natural Science');
INSERT INTO public.genre (id, language_id, name) VALUES (5, 2, 'Естественные науки');